services:
  database:
    image: postgres:13
    container_name: space_flight_news_db
    restart: always 
    ports:
      - 1234:5432
    env_file:
      - .env.docker
    volumes:
      - postgres:/var/lib/postgresql/data

  node_app:
    container_name: space_flight_news_app
    build: . 
    ports:
      - 5000:5000
    depends_on:
      - database
    env_file:
      - .env.docker

volumes:
  postgres: